client/src/components/Query/Filter/index.jsx
Fix: when editing a filter changing the operand in the dropdown would affect the pill even if the Apply button wasn't pressed
=> Fix: when editing a filter changing the operand in the dropdown would affect the pill even if the Apply button wasn't pressed

client/src/components/screens/VariantDetails/index.jsx, package.json
Same fix as in PR #200. Using a regex format that Firefox understands. Used in the Variant Details page, for Orphanet and Hpo tables.
=> Redo of PR #200

client/src/style/themes/antd-clin-theme.css, package.json
- Change autocomplete border in theme
- The theme removed the border but the hover adds one creating the layout shift so I'm setting the border as transparent instead
=> fix: #505 search bar hover

client/src/components/ConfirmationModal/index.jsx, client/src/components/screens/PatientSubmission/index.jsx, client/src/locales/en.js, client/src/locales/fr.js
- Creates a reusable confirmation modal
- Use it on the prescription form
=> feat: #449 Confirmation modal on cancel button

client/src/__tests__/PatientCreation/index.spec.tsx, client/src/helpers/fhir/api/CreatePatient.ts
- Create patient and fetus with/without RAMQ
- Create fetus with existing RAMQ
- Validate not creating patient with existing RAMQ
- Validate not creating patient wieht existing MRN
- This also fixes a case where we can't create a fetus with existing RAMQ
=> tests: adding patient creation tests

.github/CODEOWNERS
Retirer  Francis Provost des 'Owner' puisqu'il a quitté
=> fix: remove Francis Provost as owner

client/src/components/screens/Patient/components/FamilyTab/index.tsx
closes #[235]
only a proband can add a parent if does not have one already. 
Note: some old data are really messed up and can create weird results. Please make sure that data is ok before rejecting QA. Lastly, I had to remove inner buttons in menu items. It was an improper use of React.
=> fix #235 only enable add parent btn when a proband with no parents

client/src/components/screens/Patient/components/FamilyTab/components/FamilyTable.tsx, client/src/components/screens/Patient/components/PatientDetails/index.tsx
closes #[298]
Fetus gender should be consistent in patient header as well as in family tab
make sure that gender is correctly displayed for fetus AND all the other type of patient (no regression)
=> fix: #298 show fetus genre when available

client/src/helpers/providers/__tests__/extractor.mocks.ts, client/src/helpers/providers/__tests__/extractor.spec.ts, client/src/helpers/providers/extractor.ts
closes CLIN-258
Practitioner tooltip (again) crash the front-end. 
This fix may have good impact on other known data missing/invalid issues.
- sign-in any user
- go to the Prescriptions of Patient RAMQ: TEST199001012
- Mouse hover 'Médecin responsable' tooltip
=> fix: CLIN-258 - data extractor + TUs

client/src/components/screens/Patient/components/FamilyTab/components/FamilyTable.tsx, client/src/components/screens/Patient/components/FamilyTab/components/StatusCell.tsx, client/src/components/screens/Patient/components/FamilyTab/tests/mockData.ts, client/src/helpers/fhir/familyMemberHelper.ts, client/src/reducers/patient.ts, client/src/sagas/patient.js, client/src/store/FamilyMemberTypes.ts, client/src/store/GroupTypes.ts
closes #[296]
a change of status was not reflected in the displayed data
status must always be consistent.
make sure that when one changes the status that it updates, even after a refresh
=> fix: #296 make sure that member status is displayed

client/src/sagas/router.js
closes #[345]
Unable to get to the variant entity page when clicking on a variant.
when clicking on a variant in a patient page we should be able to get to the entity page
...
=> fix: #345 make sure that correct url is called for variant details

client/src/helpers/fhir/patientHelper.spec.ts, client/src/helpers/fhir/patientHelper.ts, client/src/sagas/patient.js, client/src/store/urls.ts
closes #[414]
When removing a patient from a group (family), make sure that this group is not referenced in the patient's references.
Check in the UI that all is good + check data in fhir
...
=> fix: clin-414 update removed patient with new group

client/public/index.html
https://ferlab-crsj.atlassian.net/browse/CLIN-424
Avoid using config.js from the browser cache if somehow it has been modified server side with new variables required.
=> feat: CLIN-424 - add timestamp to config.js request

client/src/components/screens/Patient/components/PatientDetails/tests/profileCard.spec.tsx, client/src/helpers/fhir/api/CreatePatient.ts, client/src/helpers/tests/mockData.ts, client/src/helpers/tests/patient.spec.ts, client/src/sagas/patient.js
Since more checks were add on the fhir server, when creating or updating a resource we must use a code system instead of a value et.
=> fix: clin-538 valueSet code for family

package.json
=> fix: clin-554 dehardcode port number in npm start script

client/src/components/screens/Patient/components/PrescriptionsTab/components/Prescriptions.tsx, client/src/components/screens/PatientSubmission/components/ClinicalInformation/index.jsx, client/src/helpers/ServiceRequestCode.ts
closes #Clin-540
Le nom de l'analyse dans l'onglet prescription de la page patient ne s'affichait plus
=> clin-540: Afficher analyse dans page patient

client/src/components/screens/Patient/components/FamilyTab/components/AddParentModal.tsx
=> fix: CLIN-572 fix organisation id in add parent modal

client/src/components/screens/Patient/components/PatientDetails/index.tsx
=> feat: clin-573 remove family type in patient details

client/src/components/Utils/getObservedIcon.tsx, client/src/components/screens/Patient/components/PrescriptionsTab/components/Prescription/ClinicalSigns.tsx, client/src/components/screens/Patient/components/PrescriptionsTab/styles.scss, client/src/components/screens/PatientSubmission/components/ClinicalInformation/index.jsx, client/src/components/screens/PatientSubmission/style.scss, client/src/style/themes/clin/main.scss
closes clin-499
Nouvelle icônes pour les signe clinique observé / non observé, dans la page patient/prescription et dans le formulaire de prescription
=> clin-499: Changer icon hpo observé

client/src/AppTest.tsx, client/src/__tests__/utils/Utils.ts, client/src/components/screens/Patient/components/FamilyTab/tests/family.spec.tsx, client/src/components/screens/Patient/components/FilesTab/tests/files.spec.tsx, client/src/components/screens/Patient/components/FilesTab/tests/mockData.tsx, client/src/components/screens/PatientCreation/tests/files.spec.tsx, client/src/helpers/fhir/__tests/PractitionerRoleHelper.spec.ts, client/src/helpers/fhir/__tests/ServiceRequestNotesHelper.spec.ts
closes #CLIN-287
Masquer les erreur, warning et log dans la console lors de l'exécution des tests automatisés.
Corriger au passage certaines erreurs dans les fichiers de tests.
=> fix: CLIN-287 Masquer les erreur et warnings dans la console

client/src/helpers/fhir/patientHelper.spec.ts
open #CLIN-868
Ajout de tests unitaires pour la validation de la RAMQ
- Ajout d'un test unitaire à faire fonctionner pour corriger le bug CLIN-868
- Un numéro composé de 4 lettres et 9 chiffres devrait être invalide
- Ajout d'autres tests unitaires pour la RAMQ
=> feat: CLIN-868 Ajout du test unitaire pour ce bug

client/src/components/screens/PatientVariant/index.tsx, client/src/components/screens/PatientVariant/styles.scss
alignement des valeur dans le tiroir d'occurrence
=> fix: clin-882 alignervaleur occurrence

client/src/helpers/fhir/__tests/PatientBuilder.spec.ts
closes #CLIN-795
Le test skippé était en attente de la correction de CLIN-795
=> feat: CLIN-795 Activation du test skippé
