client/src/components/Footer.jsx
client/src/components/Header.jsx
client/src/components/Navigation.jsx
client/src/components/screens/Patient/style.scss
client/src/components/screens/PatientSearch/index.jsx
client/src/containers/App/style.scss
client/src/helpers/struct.js
client/src/reducers/search.js

@latch2112 Ready to deploy in QA after this one.

Fix Autocomplete On Enter Table Refresh

---

client/src/components/Query/styles/statement.module.scss

Dans le dropdown myFilters maintenant les icônes sont visible en tout temps

Display icons in my filters dropdown

---

client/src/components/Query/styles/statement.module.scss
client/src/components/screens/PatientVariant/style.module.scss

Fix margin in variant header
Fix Save Message position

Save message in absolute

---

docker-compose.yml

updates to nginx config to fallback all 404s to single-page app.

nginx redirect notfound to index

---

client/src/components/screens/VariantDetails/index.jsx

Fixed issue 218. Display all consequences in consequence table, for each gene 

---

client/src/reducers/variant.js
client/src/sagas/patient.js
client/src/sagas/router.js
client/src/sagas/variant.js

https://app.zenhub.com/workspaces/clin-sprints-5c59d2c907cc4d6f39e559c2/issues/cr-ste-justine/clin-project/201

do not attempt to select defaultfilter if it does not exist

---

client/src/components/screens/VariantDetails/index.jsx

For reference, here's the bug entry. It was opened 5 years ago and apparently is in the process of being fixed just now. 
https://bugzilla.mozilla.org/show_bug.cgi?id=1225665

Modified regexes since Firefox does not support RegExp lookbehind

---

client/src/components/screens/VariantDetails/index.jsx

Svp, veuillez checker l'utilisation de `&nbsp;` est valide
https://github.com/cr-ste-justine/clin-project/issues/313

#313 - Affichage des scores

---

docker-compose-docker-local.yml
docker-compose.yml

Decoupled external proxy configuration from frontend repo

Decoupled external proxy configuration from frontend repo

---

docker-compose.yml

Changed placement to follow the convention introduced in the devops repo

Changed placement to follow the convention introduced in the devops repo

---

client/src/components/screens/PatientVariant/components/VariantNavigation.jsx
package.json

D'après les commentaires de la PR précédente j'ai simplifié le code pour le menu overflow de la page de variant

Code refactoring

---

client/src/components/screens/PatientSubmission/index.jsx
package.json

Fields RAMQ and MRN.
MRN is required, RAMQ is not, but must be a sequence of four uppercase lettres followed by 8 or 9 digits.

Saving identifier fields (RAMQ and MRN)

---

client/src/components/screens/VariantDetails/index.jsx
client/src/components/screens/VariantDetails/style.scss
package.json

Seprate the omim links, and adds a comma between them.

Adds omimLinks function to generate OMIM links.

---

client/src/components/screens/PatientSubmission/ClinicalInformation.jsx
client/src/components/screens/VariantDetails/index.jsx
package.json

Fix bug dans la page de variant 
Fix Typo dans le code dans le fichier de ClinicalInformation

fix variatDetail Bug + small typo

---

client/src/components/screens/VariantDetails/index.jsx
client/src/components/screens/VariantDetails/style.scss
package.json

Fix layout and adds space after comma

Fix layout and adds space after comma.

---

.env.production

forgotten keycloak root path fix for production.

fix: #404 forgotten keycloak root path fix for production.

---

environments/common/deployments.yml
environments/common/kustomization.yaml
environments/common/services.yml
environments/cq-qa/deployments.yml
environments/cq-qa/ingresses.yml
environments/cq-qa/kustomization.yaml

Added kubernetes orchestration

feat: 404 Added kubernetes orchestration

---

client/src/components/screens/VariantDetails/index.jsx
package.json

- Change table title
- Remove useless column
- Fix nb of patients count column

fix: cleanup variant frequency table

---

.gitignore
client/src/components/Query/Filter/ApplyButton.tsx
client/src/components/Query/Filter/FilterContent.tsx
client/src/components/Query/Filter/index.jsx
client/src/components/Query/styles/filter.module.scss
client/src/components/screens/PatientVariant/components/VariantNavigation.jsx
client/src/components/screens/PatientVariant/components/navigation.scss
package-lock.json
package.json
yarn.lock

- fix the multi level of dropdown/absolute positioning it add
- fixes the main issue (back button was closing the popup)
- Small refactoring to help understand the filter components

fix: #538 Variant filter back

---

client/src/components/Table/HeaderCellWithTooltip.tsx
client/src/components/Table/HeaderCustomCell.tsx
client/src/components/Table/index.jsx
client/src/components/Table/style.scss
client/src/components/screens/PatientVariant/index.jsx
client/src/components/screens/PatientVariant/style.scss
package.json

fixes:
- https://github.com/ferlab-ste-justine/clin-project/issues/539 Checkbox header to select all variants
- https://github.com/ferlab-ste-justine/clin-project/issues/540 Header tooltip for description

fix: #539, #540 Refactor variant table headers

---

.github/workflows/publish_image_sha.yml
.github/workflows/publish_image_tag.yml

Changed image repo to teams organization

feat: #689 Changed image repo to teams organization

---

client/src/components/screens/PatientSubmission/components/ClinicalInformation/components/MrnItem.tsx
client/src/components/screens/PatientSubmission/components/ClinicalInformation/index.jsx
client/src/components/screens/PatientSubmission/index.jsx
client/src/components/screens/PatientSubmission/style.scss
package.json

- Remove MRN edit
- Fix validation

fix: Fix MRN in prescription form

---

client/src/components/screens/Patient/components/PrescriptionsTab/components/PatientDetails.tsx
package.json

Thanks auto-close-tag extension

fix: Patient card useless button

---

client/src/components/screens/PatientSubmission/components/ClinicalInformation/components/FamilyStorySection.tsx
client/src/components/screens/PatientSubmission/style.scss
client/src/helpers/fhir/builder/BundleBuilder.ts
package.json

- Adding a new family condition produced an error
- Submitting a new family condition produced a back-end error
- Fix family relation style

fix/#742: Prescription form family condition fixes

---

client/src/components/screens/PatientCreation/components/FormModal/index.tsx
client/src/helpers/api.js
client/src/helpers/fhir/api/PatientChecker.ts
client/src/locales/en.js
client/src/locales/fr.js
client/src/sagas/patientCreation.ts
package.json

- MRN are unique for an hospital

fix/#734 Add MRN validation

---

client/src/__tests__/PatientCreation/index.spec.tsx
client/src/components/screens/PatientCreation/components/FormModal/index.tsx

- Prefill MRN for existing mother
- Fix MRN validaton for existing morther

fix: #791 fix mrn for existing mother

---

client/src/__tests__/PatientCreation/index.spec.tsx
client/src/components/screens/Patient/components/PrescriptionsTab/components/PatientEdit/index.tsx
client/src/components/screens/PatientCreation/components/FormModal/index.tsx
client/src/components/screens/PatientCreation/components/FormModal/styles.scss
cypress/e2e/PatientCreation/index.spec.ts

- Removes checkboxes and related flows
- Fixes some validation in the creation form related to the RAMQ
- Removes tests related to this flow

fix: #841 remove "no ramq" in patient creation and edition

---

client/src/__tests__/Patient/family.spec.tsx
client/src/components/screens/Patient/components/FamilyTab/components/FamilyTable.tsx
client/src/helpers/patient.ts
client/src/helpers/providers/patient/index.ts
client/src/reducers/patient.ts
client/src/sagas/patient.js

- Change parent family-id extension with the group they've been added to
- Update the way the family table is loaded to show always the "main patient" has first on the list

feat: CLIN-27-28 Review parent family

---

client/src/helpers/api.ts
client/src/sagas/patient.js

- Create a new group when removing a patient from a family

fix: remove parent new group

---

client/src/components/screens/Patient/components/FamilyTab/components/AddParentModal.tsx
client/src/helpers/api.ts
client/src/helpers/providers/types.ts

Depends on https://github.com/Ferlab-Ste-Justine/clin-proxy-api/pull/191

fix: CLIN-78 Adds family member gender

---

client/src/components/screens/Patient/components/FamilyTab/components/AddParentModal.tsx

Depends on https://github.com/Ferlab-Ste-Justine/clin-proxy-api/pull/192

fix: CLIN-60 Get ramq form autocompelte

---

.github/workflows/build.yml

Fix l'action de build qui reste en suspend dans les pr

fix: build actions demeure en suspend sur les PR

---

client/src/store/providers/apollo.tsx
client/src/store/providers/index.tsx
package.json
pnpm-lock.yaml

closes #[NUMERO_DU_TICKET_OU_LIEN]
Ajoute un provider pour apollo et graphql
Voir l'utilisation sur kf https://github.com/kids-first/kf-portal-ui/pull/2981

feat: added apollo/graphql

---

.env.development
client/src/store/providers/apollo.tsx
client/src/store/providers/index.tsx

closes #251
Permet a apollo d'utilise fhir ou arranger

feat: support multi backend for apollo provider

---

client/src/__tests__/PrescriptionCreation/index.spec.tsx
client/src/components/screens/PatientSubmission/components/ClinicalInformation/components/OntologyTree.tsx
client/src/components/screens/PatientSubmission/components/ClinicalInformation/index.jsx
client/src/helpers/api.ts
package.json

closes [CLIN-205](https://ferlab-crsj.atlassian.net/browse/CLIN-205)
Update HPO tree in prescriptions
- HPO tree must be shown in prescription form
- terms should be searchable
- Can be added or removed  
@claudia1296 @francisl

Fix/clin 205 hpo UI fix

---

client/src/containers/AppRouter.jsx
client/src/containers/PublicRoute.jsx
client/src/helpers/route.ts
client/src/helpers/tests/route.spec.ts
client/src/sagas/router.js

closes #clin-288
Modification de base pour regrouper les 'string' de url a la même place

basic refactor of router, to put routes in only one place

---

client/src/components/screens/Patient/components/PrescriptionsTab/components/Prescriptions.tsx

closes #258
Practitioner has a phone number with a different format than 3 parts with white space separator

fix: CLIN-258 - fix phone split npe

---

client/src/components/screens/Patient/index.jsx
client/src/store/providers/apollo.tsx
client/src/store/providers/index.tsx

fix: CLIN-207 graphql with rpt token

---

client/src/__tests__/PatientCreation/index.spec.tsx
client/src/__tests__/PrescriptionCreation/index.spec.tsx
client/src/components/screens/Patient/components/FilesTab/components/EmptyCard.tsx
client/src/components/screens/Patient/components/FilesTab/index.tsx
client/src/components/screens/Patient/components/FilesTab/tests/files.spec.tsx
client/src/components/screens/Patient/components/FilesTab/tests/mockData.tsx
client/src/store/graphql/files/actions.tsx

clin-196: ajout des tests

---

client/src/reducers/variant.js
client/src/sagas/variant.js

closes #[295]
Infinite loop on Variants tab
Sign-in any user, go to Variants tab.

fix: CLIN-295 - add getStatements fetch states

---

client/src/helpers/fhir/patientHelper.ts
client/src/sagas/patient.js

closes #[239]
when a parent is removed from a family (group), it returns to a new family (consisting only of him/her as members). Him or Her must be proband.
a member is proband when removed from a family
before
after
remove a parent and make sure the parent becomes a probant

fix: #239 make sure parent is proband again when removed from group

---

client/src/components/screens/Patient/components/FamilyTab/components/ActionsCell.tsx
client/src/components/screens/Patient/components/FamilyTab/components/FamilyTable.tsx
client/src/components/screens/Patient/components/FamilyTab/index.tsx
client/src/components/screens/Patient/components/FamilyTab/tests/family.spec.tsx
client/src/components/screens/Patient/components/FamilyTab/tests/mockData.ts
client/src/helpers/patient.ts

closes #[260]
Corrections après feeback du qa
...

fix: #260 correction of defects from qa

---

client/src/components/screens/PatientSubmission/index.jsx

clin-272 fix bouton soumettre prescription

---

client/src/components/screens/Patient/components/FilesTab/components/ActionDropdown.tsx

closes #292
changer nom fichier metadata
Nom doit être aliquot_format_META.json
...

clin-292 changer nom fichier metadata

---

client/src/components/screens/Patient/components/PrescriptionsTab/components/Prescription/Summary.tsx
client/src/components/screens/Patient/components/PrescriptionsTab/components/Prescriptions.tsx
client/src/components/screens/PatientSubmission/index.jsx
client/src/helpers/providers/__tests__/extractor.mocks.ts
client/src/helpers/providers/clinical-impression/index.ts
client/src/helpers/providers/extractor.ts
client/src/helpers/providers/types.ts
client/src/sagas/patient.js
client/src/store/urls.ts

https://ferlab-crsj.atlassian.net/browse/CLIN-328
Save age-at-event in days inside ClinicalImpression extension. Use this value in prescription summary.

fix: CLIN-328 - age-at-event

---

client/src/components/screens/PatientSearch/style.scss
client/src/containers/App/style.scss
client/src/style/themes/clin/antd-clin-theme.less
client/src/style/themes/clin/antd/inputs.less
client/src/style/themes/clin/antd/selects.less
client/src/style/themes/clin/dist/antd.css

CLIN-109: fix input and select styling

---

.eslintrc.json

fix: Add tabulation rules

---

client/src/sagas/prescriptions.ts

closes Clin-129
Lorsqu'on soumet une prescription, on doit afficher l'onglet correspondant

clin-129: afficher bon onglet prescription

---

client/src/sagas/router.js

closes #CLIN-365
more rescrictive catch all on route changes

fix: CLIN-365 CLIN-36 more rescrictive catch all on route changes

---

client/src/components/screens/PatientSubmission/index.jsx

[buildHpoObservation](https://ferlab-crsj.atlassian.net/browse/CLIN-325)
Subject is missing when building HPO Observation

fix: CLIN-325 - add PHENO subject

---

client/src/components/screens/PatientSubmission/index.jsx
client/src/helpers/fhir/builder/ObservationBuilder.ts

https://ferlab-crsj.atlassian.net/browse/CLIN-326
Observation status is always `final`

fix: CLIN-326 - default obs status is always final

---

client/public/index.html

https://ferlab-crsj.atlassian.net/browse/CLIN-424
Side effect with Keycloak iframe on QA, need to revert this change.

fix: CLIN-424 - revert config.js

---

client/src/actions/patientCreation.ts
client/src/components/screens/PatientCreation/components/FormModal/index.tsx
client/src/helpers/fhir/api/CreatePatient.ts
client/src/sagas/patientCreation.ts

closes #[313
when a fetus is created from its mother we wish the chosen gender be reflected after its creation.
Create a fetus choose its gender and make sure that it is reflected on its page.

fix: clin-313 create a fetus with choosen gender from form

---

client/src/actions/patientCreation.ts
client/src/components/screens/PatientCreation/components/FormModal/index.tsx
client/src/helpers/fhir/patientHelper.spec.ts
client/src/helpers/fhir/patientHelper.ts
client/src/sagas/patientCreation.ts

closes #[320]
We want to allow only one fetus per potential patient maximum.

fix: clin-320 avoid creating more than one fetus

---

client/src/components/screens/Patient/components/PatientDetails/index.tsx

fix: clin-320 hide birthday if fetus

---

client/src/components/screens/PatientSubmission/components/ClinicalInformation/components/FamilyStorySection.tsx
client/src/components/screens/PatientSubmission/components/ClinicalInformation/components/InvestigationSection.tsx
client/src/components/screens/PatientSubmission/components/ClinicalInformation/index.jsx
client/src/components/screens/PatientSubmission/index.jsx
client/src/reducers/patientSubmission.js

closes Clin-387
Faire afficher le champ CGH, consanguinité et condition de santé chez un membre de la famille lors de la modification de la prescription.
Corriger certaine variable problèmatique
Avant
Maintenant
...

Clin-387: Afficher tous les résultats modification prescription

---

client/src/components/screens/PatientSearch/components/PatientTable.tsx

feat: clin-392 change family column

---

client/src/components/screens/Patient/components/StatusChangeModal/index.tsx
client/src/components/screens/PatientSubmission/index.jsx
client/src/helpers/api.ts
client/src/helpers/fhir/__tests/ServiceRequestBuilder.mocks.ts
client/src/helpers/fhir/__tests/ServiceRequestBuilder.spec.ts
client/src/helpers/fhir/builder/ServiceRequestBuilder.ts
client/src/helpers/fhir/types.ts
client/src/store/urls.ts

https://ferlab-crsj.atlassian.net/browse/CLIN-461
Save the valueReference of status approver + refractoring of ServiceRequestBuilder + TUs

feat: CLIN-461 - add procedure directed by + refractor

---

client/src/components/screens/Patient/components/PrescriptionsTab/components/Prescriptions.tsx
client/src/components/screens/Patient/components/PrescriptionsTab/styles.scss
client/src/containers/App/style.scss
client/src/style/themes/clin/antd-clin-theme.less
client/src/style/themes/clin/dist/antd.css

changement rapide des couleurs pour être fidèle a la maquette figma

clin-450: fix couleur prescription

---

client/src/components/screens/search/search.module.scss

closes #clin-516
closes #[NUMERO_DU_TICKET_OU_LIEN]
- supprimer la bordure 
- augmentation taille
/patient/search

Clin 516 supprimer la bordure et augmentation taille

---

client/src/helpers/fhir/patientHelper.ts

fix: CLIN-430 - change group-member-status system value

---

client/src/style/themes/clin/antd-clin-theme.less
client/src/style/themes/clin/antd/drawer.less

closes #[NUMERO_DU_TICKET_OU_LIEN]
...

CLIN-444: Add style for clin-ui

---

client/src/components/screens/search/search.module.scss

CLIN-511: fix overflow border from iframe

---

client/src/__tests__/PrescriptionCreation/index.spec.tsx
client/src/helpers/api.ts

closes #493
Fix testes qui échouaient

clin-493 fix test

---

client/src/components/screens/Patient/components/PrescriptionsTab/components/Prescriptions.tsx
client/src/helpers/fhir/types.ts
client/src/helpers/providers/service-request/index.ts
client/src/helpers/providers/types.ts

closes Clin-541
Afficher le champs Laboratoire de diagnostic dans page patient prescription

clin-541 afficher ldm

---

client/src/components/screens/PatientVariant/index.tsx
client/src/components/screens/search/index.tsx

pass language to clin-ui iframe

clin-567 pass language to clin-ui

---

client/src/components/screens/Patient/components/FamilyTab/components/AddParentModal.tsx
client/src/components/screens/PatientSearch/components/PatientTable.tsx
client/src/helpers/search/types.ts

fix: clin-566 take into account change in patient index

---

client/src/components/screens/Patient/components/PatientDetails/tests/profileCard.spec.tsx
client/src/components/screens/Patient/index.jsx
client/src/locales/en.js
client/src/locales/fr.js
client/src/reducers/patient.ts

closes #Clin-565
Changer nom onglet famille pour onglet patient, mettre par défaut

clin-565 changer nom onglet famillle

---

client/src/__tests__/PatientCreation/index.spec.tsx
client/src/components/screens/PatientCreation/components/FormModal/index.tsx
client/src/locales/en.js
client/src/locales/fr.js
client/src/reducers/patientCreation.ts
client/src/sagas/patientCreation.ts

feat: CLIN-571 remove ramq confirmation

---

client/src/components/Utils/getGenderIcon.tsx
client/src/components/screens/Patient/components/PatientHeader/components/FetusHeader.tsx
client/src/components/screens/Patient/components/PatientHeader/components/ProbandHeader.tsx

closes Clin-413
Mauvaise icone pour le header de la page d'un fétus

Clin-413 fix icon sexe fetus

---

client/src/components/screens/Patient/components/FilesTab/components/EmptyCard.tsx
client/src/components/screens/Patient/components/FilesTab/styles.scss

closes clin-598
Enlever texte sous titre --> _Nous n'avons pas reçu de rapport de séquençage génomique pour ce patient._

clin-598: Modifier texte onglet fichier

---

client/src/components/screens/PatientSubmission/style.scss

closesclin-499
Aucun text element selectionner Select

-clin-499: fixer le text du select

---

client/src/components/screens/PatientVariant/style.scss

CLIN-620: Fix igv style

---

client/src/components/screens/PatientSubmission/index.jsx
client/src/helpers/fhir/fhir.js

Clin-615: Clean fhir File deadCode

---

client/src/components/screens/PatientCreation/components/FormModal/index.tsx

fix: CLIN-611 avoid checking for uniqueness of mrn when fetus

---

client/src/helpers/api.ts

https://ferlab-crsj.atlassian.net/browse/CLIN-685
Extract the PDF fileName from response header if available.

feat: CLIN-299 - extract PDF fileName from response header

---

client/src/components/screens/Patient/components/PrescriptionsTab/components/Prescriptions.tsx

closes #543
Metttre l'heure de lastupdated de la prescription a l'heure local

Clin-543: fix lastupdated heure

---

client/src/components/Utils/getGenderIcon.tsx
client/src/components/screens/PatientCreation/components/FormModal/index.tsx

closes Clin-732
Permettre de nouveau la création de patient

Clin-732: fix reparation creation patient

---

client/src/components/screens/PatientSubmissionEdit/components/ClinicalInformation/components/FamilyStorySection.tsx
client/src/components/screens/PatientSubmissionEdit/components/ClinicalInformation/components/InvestigationSection.tsx
client/src/components/screens/PatientSubmissionEdit/components/ClinicalInformation/components/MrnItem.tsx
client/src/components/screens/PatientSubmissionEdit/components/ClinicalInformation/components/MrnItemCreation.tsx
client/src/components/screens/PatientSubmissionEdit/components/ClinicalInformation/components/OntologyTree.tsx
client/src/components/screens/PatientSubmissionEdit/components/ClinicalInformation/index.jsx
client/src/components/screens/PatientSubmissionEdit/components/RamqWarningModal.tsx
client/src/components/screens/PatientSubmissionEdit/index.jsx
client/src/containers/AppRouter.jsx
client/src/helpers/route.ts
client/src/sagas/router.js

closes https://ferlab-crsj.atlassian.net/browse/CLIN-745
No frontend validation when. editing the prescription edit form

fix: #clin-745 remove prescription edit form validation

---

client/src/helpers/providers/extractor.ts

closes Clin-726
Enlever la virgule dans le format du nom du medecin prescripteur

Fix: clin-726 fix format nom

---

client/src/__tests__/PrescriptionCreation/index.spec.tsx
client/src/components/screens/PatientCreation/tests/files.spec.tsx

Réactivation des tests PatientCreation et modification des tests PrescriptionCreation

Ajout des tests PatientCreation

---

client/src/locales/fr.js

closes #724
fix petites typos page prescription

fix: CLIN-724 corriger typo prescription

---

.env.development
README.md
client/src/bridge/index.ts
client/src/components/screens/PatientVariant/index.tsx
client/src/components/screens/search/index.tsx
client/src/helpers/EnvironmentVariables.ts

closes #clin-774
- fixes bridge to only trigger callbacks related to the registered event
- fix origin validation
- remove unneeded variable CLIN_UI (should now use clin-ui-dev-proxy)

fix: #clin-774 fix bridge communication

---

client/src/components/screens/PatientSubmission/components/ClinicalInformation/components/InvestigationSection.tsx

Ajout de l'investigation dans les champs non-validadé
Dépend de https://github.com/Ferlab-Ste-Justine/clin-fhir-server/pull/89

Clin 770 champ optionel creation prescription investigation

---

client/src/components/screens/PatientSubmission/components/SecondPage.tsx

closes #clin-760
- Lorsqu'un résident soumet une prescription, le modal doit lui demander d'assigner un médecin prescripteur
- Soumettre une prescription en tant que résident
@kstonge

Clin 760 assign doctor to resident

---

client/src/components/screens/Patient/components/FamilyTab/components/PositionCell.tsx
client/src/components/screens/Patient/components/PatientDetails/ProfileCard.tsx
client/src/components/screens/Patient/components/PatientHeader/components/ProbandHeader.tsx
client/src/locales/en.js
client/src/locales/fr.js

traduction en francais du mot proband pour Cas-Index

fix: CLIN-814 traduction proband

---

client/src/components/screens/Patient/components/PrescriptionsTab/components/NoPrescription.tsx

[CLIN-870](https://ferlab-crsj.atlassian.net/browse/CLIN-870)
closes [CLIN-870](https://ferlab-crsj.atlassian.net/browse/CLIN-870)
List d'analyse est vide lorsque le patient n'a aucun prescription
URGENT

fix: #CLIN-870 list d'analyse vide si aucune prescription

---

client/src/components/screens/PatientSubmission/components/ClinicalInformation/index.jsx

fix: CLIN-880 make sure rx analysis are displayed

---

client/src/components/screens/PatientCreation/components/FormModal/index.tsx

fix: CLIN-879 update hospitals list

---

.env.development
client/src/components/Layout/Header.tsx
client/src/containers/App/style.scss
client/src/helpers/toggleFeature.tsx

fix: CLIN-888 enlever bouton traduction

---

client/src/components/screens/Patient/components/FilesTab/components/ActionDropdown.tsx
client/src/components/screens/Patient/components/FilesTab/components/MetadataButton.tsx
client/src/helpers/FileDownload.ts
client/src/helpers/api.ts
client/src/locales/en.js
client/src/locales/fr.js

feat: CLIN-621 update metadata file

---

client/src/__tests__/PrescriptionCreation/index.spec.tsx
client/src/__tests__/mocks/mockData.ts
client/src/components/screens/Patient/components/FamilyTab/tests/family.spec.tsx
client/src/components/screens/Patient/components/FilesTab/tests/files.spec.tsx
client/src/components/screens/PatientCreation/components/ExistingModal/index.tsx
client/src/components/screens/PatientCreation/components/FormModal/index.tsx
client/src/components/screens/PatientCreation/components/ResultModal/index.tsx
client/src/components/screens/PatientCreation/components/SuccessModal/index.tsx
client/src/components/screens/PatientCreation/index.tsx
client/src/components/screens/PatientCreation/tests/files.spec.tsx
client/src/components/screens/PatientCreation/tests/mockData.ts
client/src/components/screens/PatientSubmission/components/ClinicalInformation/index.jsx
client/src/components/screens/PatientSubmission/components/SubmissionModal/index.tsx
client/src/components/screens/PatientSubmission/index.jsx

Ajout de tests d'intégration pour la création de prescription
Modification aux tests d'intégration pour la création de patient
- Utilisation des fichiers de mocks séparés des fichiers de tests
- Ajout et utilisation des propriétés data-testid

Ajout/modification tests intégration de création de patient/prescription

---

client/src/components/screens/Patient/components/FilesTab/components/MetadataButton.tsx
client/src/locales/en.js
client/src/locales/fr.js

traduction metadata tableau fichier

fix: CLIN-826 traduire metadata

---

client/src/helpers/fhir/builder/PatientBuilder.ts

https://ferlab-crsj.atlassian.net/browse/CLIN-795

fix: CLIN-795 - typo patient builder
